apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet20824githubtest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet20824githubtest 
  name: dotnet20824githubtest
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet20824githubtest 
